### PR TITLE
Add valueindex for CLEAR_USER_CODE

### LINKED ISSUE #75: CommandClass 99 (USER_CODE) ValueIndex reporting wrong
In CommandClass 99 (USER_CODE) ValueIndex 256 "Remove User Code" is being reported as `ValueIndex.UNKNOWN`

```
{
    "Label": "Remove User Code",
    "Value": 0,
    "Units": "",
    "ValueSet": false,
    "ValuePolled": false,
    "ChangeVerified": false,
    "Min": -32768,
    "Max": 32767,
    "Type": "Short",
    "Instance": 1,
    "CommandClass": "COMMAND_CLASS_USER_CODE",
    "Index": 256,
    "Node": 14,
    "Genre": "System",
    "Help": "Remove A UserCode at the Specified Index",
    "ValueIDKey": 72057594287013910,
    "ReadOnly": false,
    "WriteOnly": true,
    "Event": "valueAdded",
    "TimeStamp": 1593804665
}
```

### PR DESCRIPTION
**Pull request by firstof9**
Add valueindex for CLEAR_USER_CODE, to remove user codes from locks.

Fixes #75 

Reference:
```
{
    "Label": "Remove User Code",
    "Value": 0,
    "Units": "",
    "ValueSet": false,
    "ValuePolled": false,
    "ChangeVerified": false,
    "Min": -32768,
    "Max": 32767,
    "Type": "Short",
    "Instance": 1,
    "CommandClass": "COMMAND_CLASS_USER_CODE",
    "Index": 256,
    "Node": 14,
    "Genre": "System",
    "Help": "Remove A UserCode at the Specified Index",
    "ValueIDKey": 72057594287013910,
    "ReadOnly": false,
    "WriteOnly": true,
    "Event": "valueAdded",
    "TimeStamp": 1596659523
}
```

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Does this fix #75 ?

**Comment by firstof9** [comment]
After additional checking, it doesn't. I am unable to track down why 255 and 256 return None when using the `get_value()` function.

**Comment by MartinHjelmare** [comment]
Ok. We should still add this constant, right?

**Comment by firstof9** [comment]
It would say it's a good idea once the weird `None` return is resolved it would cover the 'Remove User Code' function.

**Comment by MartinHjelmare** [comment]
Should we wait for that fix?

**Comment by firstof9** [comment]
Well looking at https://github.com/cgarwood/python-openzwave-mqtt/blob/5a1919169a747e83f6cc397fe920c8c5c8c71732/openzwavemqtt/models/value.py#L76 if I understand it correctly, if the ValueIndex isn't defined it'll return `999` as the value, if `CLEAR_USER_CODE = 256` is added it should instead return 256.

Please correct me if I'm way off the mark.

**Comment by MartinHjelmare** [comment]
Yes, that's correct.

**Comment by firstof9** [comment]
Ok then this should fix the `None` issue as well then.

**Pull request merged**
