### PR TITLE
Add SHORT ValueType

### PR DESCRIPTION
**Pull request by DanielBaulig**
This is a dependency for https://github.com/DanielBaulig/core/commit/a8bbc6b133a8608d747394b87f89fc81ddf377a4 which fixes https://github.com/home-assistant/core/issues/38307

### CODE REVIEW

**Comment by marcelveldt** [comment]
Thanks!

**Comment by marcelveldt** [comment]
We'll publish new version of the lib to pypi later this week. There are a few other things that need adjustment.

**Comment by DanielBaulig** [comment]
@marcelveldt Still intending on publishing a new version this week?

**Comment by marcelveldt** [comment]
Correct, I'm currently refactoring a small piece of code.

**Pull request merged**
